name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # ou a branch que você usa como principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # ou a versão que seu projeto usa

      # 3️⃣ Instalar dependências
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build do projeto
      - name: Build project
        run: npm run build

      # 5️⃣ Deploy para GitHub Pages
      - name: Deploy React to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          checkout: false  # já fizemos o checkout acima
          path: build
          install_command: npm ci
          build_command: npm run build
          caching: true
